using UnityEngine;

public class Snake : MonoBehaviour
{
    [SerializeField] float moveSpeed = 5.0f;

    Rigidbody2D rb;

    // MAKE COLLIDERS ON THE BOTTOM OF THE SNAKES FEET TO DETECT IF ITS GOING OFF THE PLATFORM OR TOUCHING ANY WALLS AND
    // MAKE IT MOVE THE OPPOSITE WAY IF SO
    // MAKE COLLIDERS ON THE BOTTOM OF THE SNAKES FEET TO DETECT IF ITS GOING OFF THE PLATFORM OR TOUCHING ANY WALLS AND
    // MAKE IT MOVE THE OPPOSITE WAY IF SO
    // MAKE COLLIDERS ON THE BOTTOM OF THE SNAKES FEET TO DETECT IF ITS GOING OFF THE PLATFORM OR TOUCHING ANY WALLS AND
    // MAKE IT MOVE THE OPPOSITE WAY IF SO
    // MAKE COLLIDERS ON THE BOTTOM OF THE SNAKES FEET TO DETECT IF ITS GOING OFF THE PLATFORM OR TOUCHING ANY WALLS AND
    // MAKE IT MOVE THE OPPOSITE WAY IF SO
    // MAKE COLLIDERS ON THE BOTTOM OF THE SNAKES FEET TO DETECT IF ITS GOING OFF THE PLATFORM OR TOUCHING ANY WALLS AND
    // MAKE IT MOVE THE OPPOSITE WAY IF SO
    // MAKE COLLIDERS ON THE BOTTOM OF THE SNAKES FEET TO DETECT IF ITS GOING OFF THE PLATFORM OR TOUCHING ANY WALLS AND
    // MAKE IT MOVE THE OPPOSITE WAY IF SO



    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
